# Generated by Django 3.1.2 on 2020-10-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_no', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tno', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=30)),
                ('cour', models.ManyToManyField(to='stu.Course')),
            ],
        ),
    ]
